    export const ApiConstants = {
        LOGIN: '/auth/login',
        REGISTER: '/auth/register',
        VERIFY_OTP: '/auth/verify-otp',
        FORGOTPASSWORD: '/auth/forgot-password',
        CHANGE_PASSWORD: '/auth/change-password',
        SEND_OTP: '/auth/send-otp',
        RESEND_OTP: '/auth/resend-otp',
        /////////////////////////////////////////
        GET_PROFILE_DATA: '/profile/get-profile-data',
        EDIT_PROFILE_DATA: '/profile/edit-profile-data',
        GET_ADDRESS: '/profile/addresses',
        SET_USER_ADDRESS: '/profile/addresses',
        ADD_FAVORITE_CATERER:'/profile/favorites',
        GET_FAVORITE_CATERER:'/profile/favorites',
        ADD_FAVORITE_CATERER:'/profile/favorites',
        DELETE_FAVORITE_CATERER:'/profile/favorites',
        GET_FAVORITE_CATERER:'/profile/favorites',
        GET_CATERER_DATA:'/user/caterers',
        GET_SINGLE_CATERER_DATA:'/user/caterers',
        GET_SUB_CATEGORY:'/user/categories',
        GET_ALL_ADDRESS:'/profile/addresses',
        GET_ORDERS:'/order/get-order',
        POST_CUSTOMER_DATA:'/user/checkout',
        POST_CANCEL_ORDER:'/order/cancel-order',
        ////////////////////////////////////////caterer side////////////////////////////////
        GET_ADMIN_CATEGORIE:'/admin/categories',
        GET_ADMIN_SUB_CATEGORIES:'/admin/categories',
        POST_ADMIN_CATEGORIE:'/admin/categories',
        DELETE_ADMIN_CATEGORIE:'/admin/categories',
        EDIT_ADMIN_CATEGORIE:'/admin/categories',
        POST_ACCEPT_ORDER:'/order/accept-order',
        POST_REJECT_ORDER:'/order/reject-order' 
    }            
